### ISSUE TITLE
ARG_MAX limited reached

### ISSUE THREAD

**Issue by TheSwindler44** [doersino/gomati#2]
Any solution to this ARG_MAX limit issue? 
Is there a way to increment montage and mogrify?

**Comment by doersino** [comment]
Thank you for teaching me about `ARG_MAX`!

It seems like you're trying to download an excessively large map (or `ARG_MAX` is really low on your system – on macOS, `getconf ARG_MAX` outputs 262144, which should be sufficient for 10Kish map tiles assuming ~25 characters per map tile filename, *i.e.*, a 25600×25600 pixel result image), which this tool isn't really designed for.

I'm sure there is a way of `montage`ing, say, 10×10 tiles at a time in a first pass and then `montage`ing the results in a second pass, which is what I assume you mean by "increment" – if you wanted to tackle that, I'd gladly accept a pull request. It might also be possible to name the files sequentially as they are downloaded, then use ImageMagick's built-in globbing to circumvent `ARG_MAX`, but that would break tile caching.

However, I think **there's a way better solution**: Shortly after writing this Bash script, I implemented an [improved variant in Python](https://github.com/doersino/aerialbot) – nominally to power a set of Twitter bots, but if you configure it to download an area around a fixed point and leave the Twitter API credentials blank, it's essentially equivalent to this tool. (Perhaps I should link to it at the top of the readme instead of in the middle of the self-indulgent FAQ section.)

**Comment by doersino** [comment]
> (Perhaps I should link to it at the top of the readme instead of in the middle of the self-indulgent FAQ section.)

Done that.

Based on your 👍 reaction, I assume your problem has been solved one way or another – if it hasn't, please don't hesitate to file another issue!
